export SHELL_SESSION_HISTORY=0
HISTSIZE=5000
HISTFILESIZE=10000
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

PATH=$PATH:$HOME/bin

export PYENV_ROOT="$HOME/.pyenv"

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
